"""Report Center — render a BastionReport to every supported format.

Formats: JSON, Markdown, HTML (dark, printable), CSV, SARIF 2.1.0, PDF, and an
evidence bundle (delegated to the Evidence Center). Every renderer runs finding
text through the secret scrubber as a final backstop, so no full secret can
appear in output even if an upstream producer forgot to mask.
"""

from __future__ import annotations

import csv
import io
import json
from pathlib import Path

from ..safety.masking import scrub_text
from ..schemas import BastionFinding, BastionReport, ReportFormat
from ..utils.logging import get_logger

_SEV_COLOR = {
    "critical": "#ff4d4f",
    "high": "#ff9f43",
    "medium": "#ffd93d",
    "low": "#4dc9ff",
    "info": "#8a94a6",
}


class ReportCenter:
    """Renders reports. Stateless; safe to construct per call."""

    def __init__(self) -> None:
        self.log = get_logger("report_center")

    # --- public API ----------------------------------------------------------
    def render(self, report: BastionReport, fmt: ReportFormat) -> str | bytes:
        report.recompute_summary()
        if fmt == ReportFormat.JSON:
            return self.to_json(report)
        if fmt == ReportFormat.MARKDOWN:
            return self.to_markdown(report)
        if fmt == ReportFormat.HTML:
            return self.to_html(report)
        if fmt == ReportFormat.CSV:
            return self.to_csv(report)
        if fmt == ReportFormat.SARIF:
            return self.to_sarif(report)
        if fmt == ReportFormat.PDF:
            return self.to_pdf(report)
        raise ValueError(f"unsupported format: {fmt}")

    def write(self, report: BastionReport, out_dir: Path,
              formats: list[ReportFormat]) -> dict[str, str]:
        """Render and write each format to ``out_dir``. Returns format->path."""
        out_dir = Path(out_dir)
        out_dir.mkdir(parents=True, exist_ok=True)
        report.recompute_summary()
        written: dict[str, str] = {}
        ext = {
            ReportFormat.JSON: "json", ReportFormat.MARKDOWN: "md",
            ReportFormat.HTML: "html", ReportFormat.CSV: "csv",
            ReportFormat.SARIF: "sarif.json", ReportFormat.PDF: "pdf",
        }
        for fmt in formats:
            if fmt == ReportFormat.EVIDENCE_BUNDLE:
                continue  # handled by the Evidence Center
            try:
                content = self.render(report, fmt)
                path = out_dir / f"{report.report_id}.{ext[fmt]}"
                if isinstance(content, bytes):
                    path.write_bytes(content)
                else:
                    path.write_text(content, encoding="utf-8")
                written[fmt.value] = str(path)
            except Exception as exc:  # noqa: BLE001 - one bad format must not sink the rest
                self.log.warning("failed to render %s: %s", fmt.value, exc)
        report.formats = [f for f in formats if f.value in written]
        report.output_paths = written
        return written

    # --- renderers -----------------------------------------------------------
    def to_json(self, report: BastionReport) -> str:
        # Scrub the serialized document as a final backstop: even if a producer
        # left secret-shaped text in a finding, it never reaches the JSON file.
        return scrub_text(json.dumps(report.to_dict(), indent=2, ensure_ascii=False))

    def to_markdown(self, report: BastionReport) -> str:
        s = report.summary
        lines = [
            f"# {report.title}",
            "",
            f"- **Generated:** {report.generated_at}",
            f"- **Generated by:** {report.generated_by}",
            f"- **Modules:** {', '.join(report.modules) or '—'}",
            f"- **Report ID:** `{report.report_id}`",
            "",
            "## Executive summary",
            "",
            s.headline,
            "",
            "| Severity | Count |",
            "| --- | --- |",
        ]
        for sev in ("critical", "high", "medium", "low", "info"):
            if s.by_severity.get(sev):
                lines.append(f"| {sev} | {s.by_severity[sev]} |")
        lines += ["", "## Findings", ""]
        for f in sorted(report.findings, key=lambda x: x.priority_score, reverse=True):
            lines += self._finding_markdown(f)
        lines += ["", "---", "", "_GreyNOC Bastion — local-first defensive report. "
                  "No full secrets are included. Findings are evidence-backed; "
                  "validate drafts before acting._"]
        return scrub_text("\n".join(lines))

    def _finding_markdown(self, f: BastionFinding) -> list[str]:
        out = [
            f"### [{f.severity.value.upper()}] {f.title}",
            "",
            f"- **Confidence:** {f.confidence.value}",
            f"- **Category:** {f.category.value}",
            f"- **Source:** {f.source}",
            f"- **Affected:** `{f.affected}`",
            f"- **Validation status:** {f.validation_status.value}",
            f"- **Correlation ID:** `{f.correlation_id}`",
            f"- **Timestamp:** {f.timestamp}",
            "",
            f"**Why it matters:** {f.why_it_matters}",
            "",
            f"**Recommended action:** {f.recommended_action}",
        ]
        if f.evidence:
            out += ["", "**Evidence:**"]
            for ev in f.evidence:
                out.append(f"- {ev.short()}")
        if f.false_positive_notes:
            out += ["", f"**False-positive notes:** {f.false_positive_notes}"]
        if f.operator_notes:
            out += ["", f"**Operator notes:** {f.operator_notes}"]
        out.append("")
        return out

    def to_csv(self, report: BastionReport) -> str:
        buf = io.StringIO()
        writer = csv.writer(buf)
        writer.writerow([
            "correlation_id", "title", "severity", "confidence", "category",
            "source", "affected", "validation_status", "why_it_matters",
            "recommended_action", "false_positive_notes", "timestamp",
        ])
        s = _csv_safe  # neutralize spreadsheet formula injection
        for f in sorted(report.findings, key=lambda x: x.priority_score, reverse=True):
            writer.writerow([
                s(f.correlation_id), s(scrub_text(f.title)), f.severity.value,
                f.confidence.value, f.category.value, s(scrub_text(f.source)),
                s(scrub_text(f.affected)), f.validation_status.value,
                s(scrub_text(f.why_it_matters)), s(scrub_text(f.recommended_action)),
                s(scrub_text(f.false_positive_notes)), f.timestamp,
            ])
        return buf.getvalue()

    def to_sarif(self, report: BastionReport) -> str:
        """SARIF 2.1.0 — one run, rules derived from finding titles."""
        from .. import __version__
        sev_to_level = {"critical": "error", "high": "error", "medium": "warning",
                        "low": "note", "info": "note"}
        rules: dict[str, dict] = {}
        results = []
        for f in report.findings:
            rule_id = f.ref_id or f.category.value + ":" + (f.title[:40] or "finding")
            if rule_id not in rules:
                rules[rule_id] = {
                    "id": rule_id,
                    "name": scrub_text(f.title)[:120] or rule_id,
                    "shortDescription": {"text": scrub_text(f.title)[:200]},
                    "fullDescription": {"text": scrub_text(f.why_it_matters)[:1000]},
                    "defaultConfiguration": {"level": sev_to_level.get(f.severity.value, "warning")},
                }
            results.append({
                "ruleId": rule_id,
                "level": sev_to_level.get(f.severity.value, "warning"),
                "message": {"text": scrub_text(f.why_it_matters or f.title)},
                "properties": {
                    "severity": f.severity.value,
                    "confidence": f.confidence.value,
                    "validation_status": f.validation_status.value,
                    "correlation_id": f.correlation_id,
                    "recommended_action": scrub_text(f.recommended_action),
                },
                "locations": [{
                    "physicalLocation": {
                        "artifactLocation": {"uri": self._as_uri(f.affected)},
                    }
                }] if f.affected else [],
            })
        doc = {
            "$schema": "https://json.schemastore.org/sarif-2.1.0.json",
            "version": "2.1.0",
            "runs": [{
                "tool": {"driver": {
                    "name": "GreyNOC Bastion",
                    "informationUri": "https://greynoc.local/bastion",
                    "version": __version__,
                    "rules": list(rules.values()),
                }},
                "results": results,
            }],
        }
        return json.dumps(doc, indent=2, ensure_ascii=False)

    @staticmethod
    def _as_uri(affected: str) -> str:
        # Scrub: `affected` is free-form producer text (repo path, host:port,
        # connection string) and is the one SARIF field not otherwise scrubbed.
        a = scrub_text((affected or "").strip())
        if not a:
            return "unknown"
        return a.replace("\\", "/")

    def to_html(self, report: BastionReport) -> str:
        return render_html_report(report)

    def to_pdf(self, report: BastionReport) -> bytes:
        """Render a simple, valid multi-page PDF with no third-party deps."""
        return _text_to_pdf(_report_plaintext(report))


# --- CSV formula-injection neutralization -----------------------------------
# A cell whose first character is one of these is interpreted as a formula by
# Excel / LibreOffice / Google Sheets. Prefix such cells with a single quote so
# the spreadsheet treats them as literal text. See OWASP "CSV Injection".
_CSV_TRIGGERS = ("=", "+", "-", "@", "\t", "\r")


def _csv_safe(value) -> str:
    text = "" if value is None else str(value)
    if text[:1] in _CSV_TRIGGERS:
        return "'" + text
    return text


# --- HTML rendering (shared with the dashboard) -----------------------------
def _esc(text: str) -> str:
    return (
        str(text)
        .replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def render_html_report(report: BastionReport) -> str:
    report.recompute_summary()
    s = report.summary
    sev_chips = "".join(
        f'<span class="chip" style="--c:{_SEV_COLOR[k]}">{k}: {s.by_severity[k]}</span>'
        for k in ("critical", "high", "medium", "low", "info") if s.by_severity.get(k)
    )
    rows = []
    for f in sorted(report.findings, key=lambda x: x.priority_score, reverse=True):
        ev_html = "".join(f"<li>{_esc(scrub_text(e.short()))}</li>" for e in f.evidence)
        rows.append(f"""
        <details class="finding sev-{f.severity.value}">
          <summary>
            <span class="badge" style="--c:{_SEV_COLOR.get(f.severity.value, '#888')}">{_esc(f.severity.value)}</span>
            <span class="ftitle">{_esc(scrub_text(f.title))}</span>
            <span class="fmeta">{_esc(f.category.value)} · {_esc(f.confidence.value)} confidence · {_esc(f.validation_status.value)}</span>
          </summary>
          <div class="fbody">
            <p><strong>Affected:</strong> <code>{_esc(scrub_text(f.affected))}</code></p>
            <p><strong>Why it matters:</strong> {_esc(scrub_text(f.why_it_matters))}</p>
            <p><strong>Recommended action:</strong> {_esc(scrub_text(f.recommended_action))}</p>
            {'<p><strong>Evidence:</strong></p><ul>' + ev_html + '</ul>' if ev_html else ''}
            {'<p class="fp"><strong>False-positive notes:</strong> ' + _esc(scrub_text(f.false_positive_notes)) + '</p>' if f.false_positive_notes else ''}
            <p class="cid">Correlation ID: <code>{_esc(f.correlation_id)}</code> · {_esc(f.timestamp)} · source: {_esc(scrub_text(f.source))}</p>
          </div>
        </details>""")

    findings_html = "\n".join(rows) or '<p class="empty">No findings.</p>'
    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{_esc(report.title)}</title>
<style>{REPORT_CSS}</style></head>
<body>
<div class="report">
  <header>
    <div class="brand">GreyNOC <b>Bastion</b></div>
    <h1>{_esc(report.title)}</h1>
    <div class="meta">Generated {_esc(report.generated_at)} · modules: {_esc(', '.join(report.modules) or '—')} · <code>{_esc(report.report_id)}</code></div>
  </header>
  <section class="summary">
    <h2>Executive summary</h2>
    <p class="headline">{_esc(s.headline)}</p>
    <div class="chips">{sev_chips or '<span class="chip" style="--c:#4caf50">no findings</span>'}</div>
  </section>
  <section class="findings">
    <h2>Findings <span class="count">{len(report.findings)}</span></h2>
    {findings_html}
  </section>
  <footer>
    GreyNOC Bastion — local-first defensive report. No full secrets are included.
    Findings are evidence-backed; validate drafts before acting.
  </footer>
</div>
</body></html>"""


REPORT_CSS = """
:root{--bg:#0b0f14;--panel:#141b24;--panel2:#1b2430;--ink:#e6edf3;--muted:#8a94a6;--line:#243040;--accent:#4dc9ff;}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--ink);font:15px/1.5 -apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif}
.report{max-width:960px;margin:0 auto;padding:32px 20px}
header .brand{color:var(--muted);letter-spacing:.14em;text-transform:uppercase;font-size:12px}
header .brand b{color:var(--accent)}
h1{margin:.2em 0;font-size:26px}
.meta{color:var(--muted);font-size:13px}
h2{font-size:18px;border-bottom:1px solid var(--line);padding-bottom:6px;margin-top:32px}
.summary .headline{font-size:16px}
.chips{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}
.chip{border:1px solid var(--c);color:var(--c);border-radius:999px;padding:3px 12px;font-size:13px;font-weight:600}
.count{background:var(--panel2);color:var(--muted);border-radius:999px;padding:1px 10px;font-size:13px;margin-left:6px}
.finding{background:var(--panel);border:1px solid var(--line);border-left:4px solid var(--c,#888);border-radius:8px;margin:10px 0;overflow:hidden}
.finding.sev-critical{--c:#ff4d4f}.finding.sev-high{--c:#ff9f43}.finding.sev-medium{--c:#ffd93d}.finding.sev-low{--c:#4dc9ff}.finding.sev-info{--c:#8a94a6}
.finding summary{cursor:pointer;padding:12px 14px;display:flex;gap:10px;align-items:center;flex-wrap:wrap}
.badge{background:var(--c);color:#0b0f14;font-weight:700;border-radius:4px;padding:1px 8px;font-size:12px;text-transform:uppercase}
.ftitle{font-weight:600}
.fmeta{color:var(--muted);font-size:12px;margin-left:auto}
.fbody{padding:0 16px 14px;border-top:1px solid var(--line)}
.fbody code{background:var(--panel2);padding:1px 6px;border-radius:4px;color:var(--accent)}
.fbody .cid{color:var(--muted);font-size:12px}
.fbody .fp{color:#ffd93d}
.empty{color:var(--muted)}
footer{margin-top:32px;padding-top:14px;border-top:1px solid var(--line);color:var(--muted);font-size:12px}
@media print{body{background:#fff;color:#111}.finding{break-inside:avoid}.report{max-width:none}
 .finding[open] .fbody,.fbody{display:block}details>summary{list-style:none}}
"""


def _report_plaintext(report: BastionReport) -> str:
    report.recompute_summary()
    lines = [
        report.title,
        "=" * len(report.title),
        f"Generated: {report.generated_at}",
        f"Report ID: {report.report_id}",
        f"Modules: {', '.join(report.modules) or '-'}",
        "",
        "EXECUTIVE SUMMARY",
        report.summary.headline,
        "",
        "FINDINGS",
    ]
    for f in sorted(report.findings, key=lambda x: x.priority_score, reverse=True):
        lines += [
            "",
            f"[{f.severity.value.upper()}] {f.title}",
            f"  Confidence: {f.confidence.value} | Category: {f.category.value} | Status: {f.validation_status.value}",
            f"  Affected: {f.affected}",
            f"  Why it matters: {f.why_it_matters}",
            f"  Recommended action: {f.recommended_action}",
            f"  Correlation ID: {f.correlation_id}",
        ]
        for ev in f.evidence[:5]:
            lines.append(f"    - {ev.short()}")
    lines += ["", "GreyNOC Bastion — local-first defensive report. No full secrets included."]
    return scrub_text("\n".join(lines))


def _text_to_pdf(text: str) -> bytes:
    """Minimal, dependency-free multi-page PDF writer for monospaced text.

    Produces a valid PDF 1.4 with Helvetica, wrapping long lines and paginating.
    Good enough for evidence-grade text reports without pulling in a PDF library.
    """
    def esc(s: str) -> str:
        return s.replace("\\", r"\\").replace("(", r"\(").replace(")", r"\)")

    # Wrap + paginate.
    max_chars = 92
    lines_per_page = 58
    raw_lines: list[str] = []
    for line in text.replace("\t", "    ").split("\n"):
        line = "".join(ch if 32 <= ord(ch) < 127 else "?" for ch in line)
        if not line:
            raw_lines.append("")
            continue
        while len(line) > max_chars:
            raw_lines.append(line[:max_chars])
            line = line[max_chars:]
        raw_lines.append(line)

    pages: list[list[str]] = [raw_lines[i:i + lines_per_page]
                              for i in range(0, len(raw_lines), lines_per_page)] or [[""]]

    objects: list[bytes] = []

    def add(obj: bytes) -> int:
        objects.append(obj)
        return len(objects)

    font_obj = add(b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>")
    page_obj_ids: list[int] = []
    content_obj_ids: list[int] = []
    for page in pages:
        stream_lines = ["BT", "/F1 10 Tf", "12 TL", "50 780 Td"]
        for ln in page:
            stream_lines.append(f"({esc(ln)}) Tj")
            stream_lines.append("T*")
        stream_lines.append("ET")
        stream = "\n".join(stream_lines).encode("latin-1", "replace")
        content_id = add(b"<< /Length %d >>\nstream\n%s\nendstream" % (len(stream), stream))
        content_obj_ids.append(content_id)
        page_obj_ids.append(-1)  # placeholder, fixed below

    pages_parent_id = len(objects) + len(pages) + 1  # reserve
    # Create page objects now that we know the parent id.
    real_page_ids: list[int] = []
    for content_id in content_obj_ids:
        pid = add(
            b"<< /Type /Page /Parent %d 0 R /MediaBox [0 0 612 792] "
            b"/Resources << /Font << /F1 %d 0 R >> >> /Contents %d 0 R >>"
            % (pages_parent_id, font_obj, content_id)
        )
        real_page_ids.append(pid)
    kids = " ".join(f"{pid} 0 R" for pid in real_page_ids).encode()
    pages_id = add(b"<< /Type /Pages /Count %d /Kids [%s] >>" % (len(real_page_ids), kids))
    catalog_id = add(b"<< /Type /Catalog /Pages %d 0 R >>" % pages_id)

    # Assemble file with xref.
    out = io.BytesIO()
    out.write(b"%PDF-1.4\n%\xe2\xe3\xcf\xd3\n")
    offsets = [0] * (len(objects) + 1)
    for i, obj in enumerate(objects, start=1):
        offsets[i] = out.tell()
        out.write(b"%d 0 obj\n" % i)
        out.write(obj)
        out.write(b"\nendobj\n")
    xref_pos = out.tell()
    out.write(b"xref\n")
    out.write(b"0 %d\n" % (len(objects) + 1))
    out.write(b"0000000000 65535 f \n")
    for i in range(1, len(objects) + 1):
        out.write(b"%010d 00000 n \n" % offsets[i])
    out.write(b"trailer\n<< /Size %d /Root %d 0 R >>\n" % (len(objects) + 1, catalog_id))
    out.write(b"startxref\n%d\n%%%%EOF\n" % xref_pos)
    return out.getvalue()
